### PR TITLE
Added redirect link for CMS-W courses

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
## Description

Adds link to redirect CMS-W courses to search url

## Motivation and Context

This PR is for the issue https://github.com/mitodl/ol-infrastructure/issues/1013. We recently updated departments of some courses to CMS-W which is causing old departments links to failing. This PR should redirect to search rather then throwing a 404.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pdpinch** [comment]
Can you put the redirect in alphabetical order?

**Comment by Wassaf-Shahzad** [comment]
> Can you put the redirect in alphabetical order?

Sure

**Review by shaidar — APPROVED** [review]

**Comment by Wassaf-Shahzad** [comment]
> Can you put the redirect in alphabetical order?

All of them ?

**Comment by pdpinch** [comment]
> Can you put the redirect in alphabetical order?

> All of them ?

Good question. I was thinking just the two that you added.

**Comment by Wassaf-Shahzad** [comment]
> > Can you put the redirect in alphabetical order?
> 
> > All of them ?
> 
> Good question. I was thinking just the two that you added.

Aren't they already, since /course is above /fairuse

**Comment by Wassaf-Shahzad** [comment]
> @Wassaf-Shahzad it seems to me there's already a line here that should take care of this redirect, but it doesn't seem to work?
> 
> https://github.com/mitodl/ol-infrastructure/blob/b12b1704c2b2b1ba52f38819bb2437971e49549a/src/ol_infrastructure/applications/ocw_site/redirect_dict#L369
> 
> Can you tell why not?

@pdpinch Sorry, I cant figure this out. @shaidar is there a way to test this locally.

**Comment by blarghmatey** [comment]
The redirect dictionary is only set up to handle specific site redirects, not prefix redirects. There had been some discussion about handling prefix redirects but that work hasn't happened yet.

**Comment by Wassaf-Shahzad** [comment]
@blarghmatey @pdpinch is this pr ok to merge

**Comment by pdpinch** [comment]
Sorry @blarghmatey I don't understand. 

We want to redirect from https://ocw.mit.edu/courses/comparative-media-studies-writing/ to https://ocw.mit.edu/search/?d=Comparative%20Media%20Studies%2FWriting

I don't see how that requires a "prefix redirect" ? 

Moreover, I don't see how @Wassaf-Shahzad 's change is significantly different.

**Comment by pdpinch** [comment]
@Wassaf-Shahzad this needs a rebase

**Comment by blarghmatey** [comment]
I just assumed it was intended to be a prefix because of the trailing `/`. If it is intended as the entire URL then it should work without issue.

**Comment by Wassaf-Shahzad** [comment]
@blarghmatey should I merge this ?

**Comment by blarghmatey** [comment]
:+1:

**Pull request merged**
