### PR TITLE
config: enable certificate_html_view to enable certificate option in studio (MITxOnline)

### PR DESCRIPTION
**Pull request by arslanashraf7**
# What are the relevant tickets?
Part of debugging https://github.com/mitodl/hq/issues/1630, Specifically https://github.com/mitodl/hq/issues/1630#issuecomment-1640111969 comment.

# Description (What does it do?)
- This would enable a setting `Certificates` in the Studio course settings
- Enabling the `Certificates` would make it easy for us to check if a course has active certificate pages created.
- Would also allow us to `Activate/Deactivate` the certificate pages.
- More details are in https://github.com/mitodl/hq/issues/1630#issuecomment-1640111969

# Screenshots (if appropriate):
**Certificate setting in Studio**
image

**Certificate Page in Studio**

image

# How can this be tested?
Once deployed, We should see `Certificate` setting in studio course settings. (See screenshot above)

# Additional Context
This is probably just a temporary change to debug a few things in MITxOnline studio, It's possible that we would revert this once our debugging is complete.

If you think, To enable a feature temporarily have another solution than a PR, Please let me know.

### CODE REVIEW

**Comment by arslanashraf7** [comment]
pre-commit is failing on this PR, But that's also failing on the main, something to do with the ol-concourse setting's text length.

**Review by blarghmatey — APPROVED** [review]

**Comment by arslanashraf7** [comment]
@blarghmatey Should this be deployed automatically on QA instance of MITxOnline? I tried checking on https://studio-qa.mitxonline.mit.edu/course/course-v1:Arbisoft+ARB_CRT_0001+2022_T1 if the `Certificates` setting is now available but I don't see it yet.

**Comment by pdpinch** [comment]
There were some issues with QA deployments this week (partially due to edx-sysadmin), but I think everything was working as of Thursday afternoon.  Please check again. 

If the setting still isn't deploying, you may need to follow up with Sar since Tobias is out until Wednesday.

**Comment by arslanashraf7** [comment]
Thanks, I checked the QA again and I can see the certificate settings now on a sample course https://studio-qa.mitxonline.mit.edu/certificates/course-v1:Arbisoft+ARB_CRT_0001+2022_T1.

But on Production I still don't see, Wither we'll need to wait on our weekly production release or get this setting deployed on production as well. What do you think, should we wait for weekly release or get it deployed on production now?

**Comment by pdpinch** [comment]
We should wait for the weekly release, so the MITx team has an opportunity to test and discover any side effects.

**Pull request merged**
