### PR TITLE
Adding ol-configuration-management to consolidate infrastructure management as a monorepo

### PR DESCRIPTION
**Pull request by blarghmatey**

### CODE REVIEW

**Comment by shaidar** [comment]
👍

**Comment by markbreedlove** [comment]
The addition to the README refers to a `src/components` directory but I do not see it in this branch.

**Comment by markbreedlove** [comment]
I'm not sure how well I can evaluate it without having worked with pyinfra yet. Maybe some usage examples would help. Otherwise, I don't notice any issues.

**Comment by blarghmatey** [comment]
I was mainly just looking for feedback on actually merging the repos, not so much a review of the PyInfra code as that has already been reviewed and merged in the other repository.

**Pull request merged**
