### PR TITLE
add redirect for YouTube comment policy

### PR DESCRIPTION
**Pull request by pdpinch**
## Description

Adds a redirect for /terms/comments/

## Motivation and Context

YouTube descriptions link to a page on the legacy site that has moved to the ZenDesk help center. 

## How Has This Been Tested?

I've tested the destination URL, but that's it. I'd like to test it on the QA server before going live. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- ~~My code follows the code style of this project. (Did you install and run the pre-commit hooks?)~~
- ~~My change requires a change to the documentation.~~
- ~~I have updated the documentation accordingly.~~

### CODE REVIEW

**Comment by pdpinch** [comment]
Is this a python-style dict? Can I add a terminal comma?

**Comment by blarghmatey** [comment]
It's actually a JSON file so unfortunately not.

**Comment by blarghmatey** [comment]
:+1:

**Comment by blarghmatey** [comment]
:+1:

**Comment by pdpinch** [comment]
So, what happens after I merge this?

**Pull request merged**
