### PR TITLE
Tm/airbyte fixup

### PR DESCRIPTION
**Pull request by blarghmatey**
This adds some fixes related to recovery after the Vault QA outage, as well as for integrating Airbyte with AWS Lake Formation

## Description
Update the Airbyte deployment to be more fully automated and update IAM permissions for interacting with necessary data lake resources.

## How Has This Been Tested?

The changes have been applied to the QA instance and the full end-to-end flow of data from source to lake and querying with Trino has been tested manually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by blarghmatey** [comment]
One thing to consider here is that I updated the consul/vault templates to read from a v2 KV mount in Vault, but we currently have a v1 mounted. I think it would be useful to be able to upgrade if everything will work, but I'm also happy to back out those template changes.

**Comment by Ardiea** [comment]
>One thing to consider here is that I updated the consul/vault templates to read from a v2 KV mount in Vault, but we currently have a v1 mounted. I think it would be useful to be able to upgrade if everything will work, but I'm also happy to back out those template changes. 

Just so I understand correctly, with **this PR**, it will work with either a v1 or a v2 mount. However, as the code is right now on `main`, it will only work with a v1 mount? 

That is, you could merge this and everything would be great and you could update the mount to v2 and everything would still be great.

**Comment by blarghmatey** [comment]
Unfortunately that's not correct. I'm sure it would be possible to add some logic in the template to support V1 and V2, but as it stands right now the template will only function with v2 if this PR merges. Probably something worth investing in to paper over those differences since we currently don't have much rhyme or reason of which mounts are v1 and which are v2 and services are liable to span multiple mounts. I'll take a stab at what that might look like.

**Comment by Ardiea** [comment]
Okay, I spent the better part of the past several hours playing with this as requested and I'm not sure it is ready to be merged yet until we have a good grasp on how to make the changes needed to the data layout and secrets engine in vault first.

**Comment by blarghmatey** [comment]
I removed the v2 style lookups in the templates so that the rest of the changes don't get blocked as a result.

**Review by Ardiea — APPROVED** [review]

**Pull request merged**
