### PR TITLE
Ol-Infra-1007 Add configs for user retirement

### PR DESCRIPTION
**Pull request by asadali145**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by asadali145** [comment]
@blarghmatey @pdpinch 
Here are a few more things that we need to do but we are not sure how to manage:

- Install https://github.com/edx/tubular in edX instance at `/src`. Not sure how we are going to install it at `/src`.
- Create a virtual environment and install requirements for https://github.com/edx/tubular.
- Create a config.yml that we are going to need for https://github.com/edx/tubular. Once tubular is cloned we will have to move this to tubular.

Once all of this is set up. Here are the steps to retire a user. 

- Run the `retire_users ` command in MITxOnline to retire it from MITxOnline.
- Run the `retire_user` command in edX to retire the user in the edX. This will create a Retirement Status with a `PENDING` state.
- Activate the `tubular` virtual environment.
- Run `retire_one_learner.py <username>`. This will take a user through the retirement pipeline and eventually it will mark the retirement status as `COMPLETED` if everything goes well.
PS: For the last 3 steps in retirement, we can create a shell script that will execute these steps.

**Review by blarghmatey — COMMENTED** [review]
Small typo, but otherwise looks good.

**Comment by blarghmatey** [comment]
As far as the usage of Tubular, when I looked at the retirement scripts it seemed to be using the REST APIs, so we should be able to run that in a Concourse pipeline, removing the need to package that project into the same instance as the edX application.

For the first two steps, are those only available as management commands, or can those also be triggered via an API?

**Comment by asadali145** [comment]
> For the first two steps, are those only available as management commands, or can those also be triggered via an API?

- In MITxOnline, We do not have an API for user retirement. We can create one if we need.
- In edX, we have 2 APIs to start user retirement.
  - `api/v1/accounts/deactivate_logout/` is the one built for the users to delete the accounts.
  - `v1/accounts/bulk_retire_users` can be used by service users but it has authentication issues in edX, If we add `api/` at the start of this URL then it works fine.

Let me know if this still does not answer your question.

**Comment by blarghmatey** [comment]
Closing as a duplicate. This change was added in a previous PR.

**Pull request closed without merging**
