### PR TITLE
Adding module for handling standalone s3 buckets

### PR DESCRIPTION
**Pull request by blarghmatey**
There are some cases where we manage S3 buckets that are not associated with any application. This module is intended to handle those cases.

### CODE REVIEW

**Comment by blarghmatey** [comment]
One thing I'm debating is whether it makes any sense to have a QA stack for this module.

**Comment by shaidar** [comment]
Do those two file names kinda feel redundant given their place in the directory structure?
`Pulumu.infrastructure.aws.s3.Production.yaml`
`Pulumu.infrastructure.aws.s3.QA.yaml`

**Comment by blarghmatey** [comment]
Those files are required. That's how the stacks are defined in Pulumi.

**Comment by shaidar** [comment]
I understand they're required, but what I was referring to is that they're already in a folder called infra/aws/s3 .. so isn't kinda redundant to name them that way as well?

**Comment by blarghmatey** [comment]
No, because the file name is how it defines the stack name and the stack name needs to be fully namespaced to allow for cross-"project" stack references.

**Comment by shaidar** [comment]
👍

**Pull request merged**
