### PR TITLE
feat: update mitx logo configs

### PR DESCRIPTION
**Pull request by asadali145**
### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/3340

### Description (What does it do?)

Updates config for the MITx Residential logo updates.

### Screenshots (if appropriate):

- [ ] Desktop screenshots
- [ ] Mobile width screenshots

### How can this be tested?

- Add the configs locally and verify the logos.

### CODE REVIEW

**Comment by pdpinch** [comment]
Is it possible to use relative URLs for these settings?

**Comment by asadali145** [comment]
> Is it possible to use relative URLs for these settings?

@blarghmatey Is there a way to do that?

**Comment by asadali145** [comment]
@pdpinch OR @blarghmatey Do you know why we haven't anything at `/admin/theming/sitetheme/` for any of our apps like [MITx Online](https://courses-qa.mitxonline.mit.edu/admin/theming/sitetheme/) but the theme is still working? Locally, it is not like that and theme does work without these configs.

**Comment by blarghmatey** [comment]
The theme is configured via the `DEFAULT_SITE_THEME` value [here](https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl#L248). The theme location is controlled [here](https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp_v2/templates/edxapp/mitx/common_values.yml.tmpl#L203-L204)

In theory it _should_ be possible to use relative URLs for the logo but I don't know off-hand.

**Comment by asadali145** [comment]
Thanks @blarghmatey,

I was looking into using the relative URLs from our sites i.e. [courses-rc.xpro.mit.edu](courses-rc.xpro.mit.edu). There is something that we are missing.

Here are my findings:

- The original Open edX logo is accessible at [courses-rc.xpro.mit.edu/static/images/logo.png](courses-rc.xpro.mit.edu/static/images/logo.png). This is the same as the local Devstack environment.
- The overridden logos in themes are accessible locally at `/static/<theme>/images/logo.png` i.e. for mitxpro-theme, the logo is accessible at `localhost:18000/static/mitxpro-theme/images/logo.png` **_BUT_** for our [instances it throws 404](https://courses-rc.xpro.mit.edu/static/mitxpro-theme/images/logo.png).

What could be the possible reason behind this?

CC: @pdpinch @arslanashraf7

**Comment by blarghmatey** [comment]
Ok, so it looks like the logo URL does follow the pattern that you highlighted, as I am able to load the log for MITx Online at https://courses.mitxonline.mit.edu/static/mitxonline/images/logo.png and for residential MITx it is at https://lms.mitx.mit.edu/static/mitx/images/logo.png. For xPRO the PNG is visible at https://courses-rc.xpro.mit.edu/static/xpro/images/logo.png

So, given that, it seems that we should be able to use relative URLs (or even full URLs) pointing at the running edX platform to load the images from, rather than loading from GitHub.

For clarity, the theme names as defined in the running systems are:
- MITx Onilne: mitxonline
- Residential MITx: mitx
- MIT xPRO: xpro

Let me know if you run into any other issues. Thanks!

**Review by blarghmatey — APPROVED** [review]

**Comment by asadali145** [comment]
@blarghmatey Thanks for reviewing this PR, I have added another config in https://github.com/mitodl/ol-infrastructure/pull/2270/commits/272faa26abf585de84519bca707f9a32fcbaab72. Please have another look.

**Comment by asadali145** [comment]
Failing CI check is not related to this PR.

**Review by blarghmatey — APPROVED** [review]

**Pull request merged**
