### PR TITLE
SSO for Redash

### PR DESCRIPTION
**Pull request by Ardiea**
## Description
This will enable SSO authentication into redash via Touchstone.

## Motivation and Context
Make life easier for users. 

## How Has This Been Tested?
Slowly and manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by blarghmatey** [comment]
:+1:

**Comment by blarghmatey** [comment]
:+1:

**Comment by Ardiea** [comment]
Holding on merging this until I hear back from IS&T regarding bi-qa.odl.mit.edu metadata and their happiness level with it. I was able to quickly address their complaint today.

**Review by blarghmatey — APPROVED** [review]
:+1:

**Pull request merged**
