### PR TITLE
added link to redirect dict

### LINKED ISSUE #922: Redirect https://ocw.mit.edu/fairuse/ to ZenDesk
# User Story
The OCW team would like a redirect for their "fair use" url.  The URL "[https://ocw.mit.edu/fairuse/](https://ocw.mit.edu/fairuse/)" should redirect to a ZenDesk article "[How is all rights reserve content different from the rest of OCW content?](https://mitocw.zendesk.com/hc/en-us/articles/4414756181403-How-is-all-rights-reserved-content-different-from-the-rest-of-OCW-content-)".

# Description/Context
This URL occurs in >10,000 documents (e.g., lecture notes) and within some course pages. The team just flagged it as something they missed in the NextGen migration.

# Acceptance Criteria
Working redirect of the fair use url: https://ocw.mit.edu/fairuse/

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
## Description
Adds link to redirect dict

## Types of changes

- [x] Enhancement (improves on existing behavior)

## Ticket
Closes #922

### CODE REVIEW

**Review by blarghmatey — APPROVED** [review]
:+1:

**Comment by pdpinch** [comment]
In the future, I think these should be alphabetized.

**Comment by pdpinch** [comment]
When will this be deployed?

**Comment by blarghmatey** [comment]
This is deployed to QA now. I'll deploy to production once validated.

**Comment by pdpinch** [comment]
Looks OK to me (although I'm not sure why there's no `Temporary Redirect` after the `307` in the response): 

```
pdpinch@pdpinch2018 ~ % curl -I https://live-qa.ocw.mit.edu/fairuse 
HTTP/2 307 
retry-after: 0
location: https://mitocw.zendesk.com/hc/en-us/articles/4414756181403-How-is-all-rights-reserved-content-different-from-the-rest-of-OCW-content/
accept-ranges: bytes
date: Tue, 05 Jul 2022 15:44:58 GMT
x-served-by: cache-bos4622-BOS
x-cache: HIT
x-cache-hits: 0
strict-transport-security: max-age=300
content-length: 0
```

**Comment by blarghmatey** [comment]
This is deployed to production now.

**Pull request merged**
