### PR TITLE
Added redirects to handle course collections for legacy courses 

### LINKED ISSUE #1011: Course collection redirects
# User Story

Out on the web, there are links to legacy course collections. We have re-created these collections on the new OCW site, but the URLs are different. 

# Description/Context

OLD: https://ocw.mit.edu/courses/energy-courses
NEW: https://ocw.mit.edu/collections/energy/

OLD: https://ocw.mit.edu/courses/entrepreneurship
NEW: https://ocw.mit.edu/collections/entrepreneurship/

OLD: https://ocw.mit.edu/courses/environment-courses
NEW: https://ocw.mit.edu/collections/environment/

OLD: https://old.ocw.mit.edu/courses/intro-programming
NEW: https://ocw.mit.edu/collections/introductory-programming/

OLD: https://old.ocw.mit.edu/courses/transportation-courses
NEW: https://ocw.mit.edu/collections/transportation/

# Acceptance Criteria

- [ ] I think these are one-off redirects to add to fastly
- [ ] test them on draft/qa and then test them on production 
- [ ] I don't think they justify automated tests, but maybe that would be a good practice exercise for #991

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
## Description
Updated redirect dicts to handle course collections  for legacy courses.

## Motivation and Context

Closes #1011 

## How Has This Been Tested?

Will be tested on QA

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improves on existing behavior)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project. (Did you install and run the pre-commit hooks?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by shaidar** [comment]
👍

**Review by shaidar — APPROVED** [review]

**Comment by pdpinch** [comment]
@shaidar what happens after this is merged? Do you have to deploy it manually? What servers can we test on?

**Comment by pdpinch** [comment]
Ok, this is merged. Now what?

It doesn't seem to be active on https://live-qa.ocw.mit.edu/courses/energy-courses/ or on https:/ocw.mit.edu/courses/energy-courses/

**Comment by shaidar** [comment]
@pdpinch Sorry, I missed this. Should now be deployed on QA. Those changes still need to be manually deployed by one of us.

**Comment by pdpinch** [comment]
Ok. It looks like it's working on QA for me:

```pdpinch@pdpinch2018 course 41 % curl -I https://live-qa.ocw.mit.edu/courses/energy-courses/
HTTP/2 307 
retry-after: 0
location: https://live-qa.ocw.mit.edu/collections/energy/
accept-ranges: bytes
date: Fri, 16 Sep 2022 18:41:31 GMT
x-served-by: cache-bos4647-BOS
x-cache: HIT
x-cache-hits: 0
strict-transport-security: max-age=300
content-length: 0
```

**Pull request merged**
